### ISSUE TITLE
Incorrect track information after starting the race

### ISSUE THREAD

**Issue by JanaBobulis** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#14]
Regardless of which racer and track I choose It always returns track 1 within the renderRacerStartView();
I have been advised by one of the mentors that it might be related to the issue with the starter code. 
![920b39ed-8cd2-4c20-8dd3-331feb75d051-original](https://user-images.githubusercontent.com/71527795/115207207-4892a800-a0f3-11eb-8ac7-f0a587fcb18c.png)
![05709a56-ef41-4006-a383-f481865486ec-original](https://user-images.githubusercontent.com/71527795/115207212-492b3e80-a0f3-11eb-98e8-c0d621995462.png)

**Comment by UAnjali** [comment]
Hi,
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
