### ISSUE TITLE
Please fix this typo

### ISSUE THREAD

**Issue by ifkas** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#15]
There is a typo in the starter code, it is located on line 185 which gives an error in the console.
It is written "reuslts", where obviously should be "results".
Check the screenshot attached:
![typo](https://user-images.githubusercontent.com/987112/126137546-5b8b1c20-6479-4302-9435-bdb166384af1.png)

Thanks and see ya!

**Comment by yeunoia** [comment]
it's fixed now, I pull requested 👍🏻
