### ISSUE TITLE
Issues launching server

### ISSUE THREAD

**Issue by RookTKO** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#16]
**On the main readme the the docs tell you to use the argument before calling the executable, it should be the other way around. Instead of this:**

### WRONG
<html>
<body>

Your OS | Command to start the API
-- | --
Mac | ORIGIN_ALLOWED=http://localhost:3000 ./bin/server-osx
Windows | ORIGIN_ALLOWED=http://localhost:3000 ./bin/server.exe
Linux (Ubuntu, etc..) | ORIGIN_ALLOWED=http://localhost:3000 ./bin/server-linux

</body>
</html>

**It should be this:**

### RIGHT
<html>
<body>

Your OS | Command to start the API
-- | --
Mac |  ./bin/server-osx ORIGIN_ALLOWED=http://localhost:3000
Windows |  ./bin/server.exe ORIGIN_ALLOWED=http://localhost:3000
Linux (Ubuntu, etc..) |  ./bin/server-linux ORIGIN_ALLOWED=http://localhost:3000

</body>
</html>

**Comment by UAnjali** [comment]
Hi,
Thanks for suggesting the updates. We would request you to raise a PR for the same.
Happy Learning

**Comment by AlroySparkle** [comment]
I tried this one but it gave me error "'.' is not recognized as an internal or external command,
operable program or batch file."

edit:
Seems another two issues have been appeared, when copy repository, files in bin will be extension-less, and name has been changed
