### ISSUE TITLE
Missing close brace for returned promise

### ISSUE THREAD

**Issue by fanyui** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#2]
https://github.com/udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter/blob/9d55121bc12f13e0c9518d5b6ccb3e61bc162025/src/client/assets/javascript/index.js#L136

This line lacks a closing `)` brace in the starter code.

**Comment by Alexisricher1** [comment]
Solved in previous commit a1720b92bbe0d9e9cfbe893bbb0d8f76cc363683

**Comment by UAnjali** [comment]
Hi,
We are closing out the issue because it has already been addressed in another issue recently. 
Thank you
