### ISSUE TITLE
Insufficient(no) parameters supplied to function

### ISSUE THREAD

**Issue by fanyui** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#3]
https://github.com/udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter/blob/9d55121bc12f13e0c9518d5b6ccb3e61bc162025/src/client/assets/javascript/index.js#L87
The function signature is 
`function renderRaceStartView(track, racers)` 
However it's call on the above line without params and inside the function, it looks like the function cannot do without the track hence the function will raise a reference error when executing this line ```<h1>Race: ${track.name}</h1>``` I think it should either implicitly be specified as `Todo` or to the minimum the track be passed.

**Comment by UAnjali** [comment]
Hi,
Thanks for suggesting the issue. If you still see the issue, we would suggest you raise a PR for the same.
Thank you
