### ISSUE TITLE
handleAccelerate inconsistent signature and function call.

### ISSUE THREAD

**Issue by fanyui** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#4]
https://github.com/udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter/blob/9d55121bc12f13e0c9518d5b6ccb3e61bc162025/src/client/assets/javascript/index.js#L73

handleAccelerate is invoked at this line with the event target as param however the signature does not have parameters.

**Comment by UAnjali** [comment]
Hi,
We are closing out the issue because it has already been addressed in another issue recently. 
Thank you
