### ISSUE TITLE
renderAt throws an error length of null

### ISSUE THREAD

**Issue by fanyui** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#5]
https://github.com/udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter/blob/9d55121bc12f13e0c9518d5b6ccb3e61bc162025/src/client/assets/javascript/index.js#L300

function renderAt(element, html) takes in the parameters element`Either the id or the class name of the element at which to render` and the HTML `the actual content to render`  the check inside 
```
	if (element.match(/^\./).length) {
		node = document.getElementsByClassName(element)
	}

	if (element.match(/^#/).length) {
		node = document.getElementById(element)
	}
```
 Either of the condition will always fail ie when the id is supplied the class will fail as the evaluation
element.match(/^#/).length will be evaluating length of null the reverse is true.

**Comment by ehabhamdy** [comment]
I am also experiencing the same issue and had to adjust it to execute the code. Here is what I did:
```
if (element.match(/^\./) !== null) {
    node = document.getElementsByClassName(element.slice(1))
}

if (element.match(/^#/) !== null) {
    node = document.getElementById(element.slice(1))
}
```

I had to remove the first character as the passed starts with either a `#` or `.` which are not compatible with the `getElementByID` and `getElementByClassName` respectively.

**Comment by UAnjali** [comment]
Hi,
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
